### ISSUE TITLE
vange.rs domain

### ISSUE THREAD

**Issue by lolmaus** [kvark/vange-rs#86]
Hi!

I'm paying for the vange.rs domain. Currently, it's redirecting to this GitHub repo.

I'm happy to keep paying while the project stays active. 

But I don't see the domain used in any way. If nobody needs it for any purpose, I'd rather stop paying.

Thoughts?

**Comment by kvark** [comment]
@lolmaus I'd really like to use it in the future. As vange-rs is built on WebGPU API, there is going to be a point, possibly next year, where we'll start compiling it for the Web. So the end goal would be having it running in the browser, where having a good domain name would be great.

I don't want you to spend money on the domain that isn't used, and I don't want to feel pressured to get the Web going just because your domain is waiting. Perhaps, you could transfer the domain to me, so that I can pay for it?

**Comment by lolmaus** [comment]
I'll keep paying for it so that I can feel being part of the thing you have going on here.

I will transfer the domain to you when you *insist* on it.

Payed it up until December 2020.

Can you please add the domain to the description field of the repo?

**Comment by kvark** [comment]
Done. Please reach back if you change your mind :) And thank you!

**Comment by lolmaus** [comment]
![Lipuringa](https://user-images.githubusercontent.com/200884/69649258-d3e24800-107d-11ea-816d-d95d54b41d30.png)
